- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Node.js and npm
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm

- name: Clone repository
  git:
    repo: 'https://github.com/chinmaya10000/nodejs-deployment.git'
    dest: /home/ubuntu/app
    version: master

- name: Install dependencies
  npm:
    path: /home/ubuntu/app
    state: present

- name: Start the application
  command: "node /home/ubuntu/app/index.js"
  args:
    chdir: /home/ubuntu/app
  async: 1
  poll: 0