name: Deploy Node.js Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you are using

      - name: Install Ansible
        run: sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i ${{ secrets.EC2_PUBLIC_IP }}, --private-key <(echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}") ansible/node_service.yml --tags app